---
config:
  theme: mc
---
gantt
dateFormat  YYYY-MM-DD
title Diagrama de Gantt del Proyecto
axisFormat %b
section Fases del Proyecto
Concepción y análisis           :done, A1, 2025-04-01, 30d
Diseño y arquitectura           :A2, after A1, 31d
Desarrollo de contenido educativo :A3, after A2, 30d
Integración de Gamificación y Mejora :A4, after A3, 31d
Desarrollo del Manual de Usuario y Producto Final :A5, after A4, 30d
